[package]
name = "pbd-fluid-rs"
version = "0.1.0"
authors = ["Lucas V. Schuermann <lucas@lvs.io>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/bin.rs"
required-features = ["build-binary"]

[dependencies]
js-sys = "0.3.53"
wasm-bindgen = "0.2.76"
cgmath = "0.18.0"
glam = "0.17.3"
web-sys = {version = "0.3.53", features = [
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlUniformLocation',
  'WebGlProgram',
  'WebGlShader',
  'console',
]}

glium = {version = "0.30.1", optional = true}
log = {version = "0.4", optional = true}
env_logger = {version = "0.9.0", optional = true}

[features]
build-binary = ["glium", "log", "env_logger"]

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O"]