[package]
name = "pbd-fluid-rs"
version = "0.1.0"
authors = ["Lucas V. Schuermann <lucas@lvs.io>"]
edition = "2021"
publish = false

[workspace]
members = ["native", "solver"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cgmath = "0.18.0"
solver = { path = "solver" }
js-sys = { version = "0.3.53" }
wasm-bindgen = { version = "0.2.76" }
web-sys = { version = "0.3.53", features = [
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlUniformLocation',
  'WebGlProgram',
  'WebGlShader',
] }

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O3"]
